id: P006938
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20879
  title: བོད་ཀྱི་གསར་བརྗེའི་ལོ་རྒྱུས།
  author: ''
  volumes:
    e9bf31f06b3047b6bf940d5c301b4be2:
      image_group_id: I1KG20969
      title: ''
      volume_number: 1
      total_pages: 658
ebook_metadata:
  title: བོད་ཀྱི་གསར་བརྗེའི་ལོ་རྒྱུས།
  author: ''
  sku: P006938
  cover: cover.jpg
  layers:
  - pagination
