id: P006938
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:47.849729
source_metadata:
  id: bdr:W1KG20879
  title: བོད་ཀྱི་གསར་བརྗེའི་ལོ་རྒྱུས།
  author: ''
  volumes:
    6a80b6681b0e4bb1859920b0bb7583a6:
      image_group_id: I1KG20969
      title: Volume 1 of bod kyi gsar brje'i lo rgyus/
      volume_number: 1
      total_pages: 658
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
