id: I216686A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:16:44+00:00'
last_modified: '2022-06-08T12:42:34.646921+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20879
  title: བོད་ཀྱི་གསར་བརྗེའི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1EC3:
      image_group_id: I1KG20969
      title: Volume 1 of bod kyi gsar brje'i lo rgyus/
      total_pages: 658
      order: 1
      base_file: 1EC3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
